Repository faycalBordjah/Conference, pull requests merged in 2019-06, with the labels that each got.

#4 Install symfony framework
  .codacy.yml
  .env
  .gitignore
  bin/console
  composer.json
  composer.lock
  conference/.env
  conference/.gitignore
  conference/bin/console
  conference/composer.json
  conference/composer.lock
  conference/config/bootstrap.php
  conference/config/bundles.php
  conference/config/packages/cache.yaml
  conference/config/packages/dev/routing.yaml
  conference/config/packages/framework.yaml
  conference/config/packages/routing.yaml
  conference/config/packages/test/framework.yaml
  conference/config/packages/test/routing.yaml
  conference/config/routes.yaml
  conference/config/services.yaml
  conference/public/index.php
  conference/src/Controller/.gitignore
  conference/src/Kernel.php
  conference/symfony.lock
  config/bootstrap.php
  config/bundles.php
  config/packages/cache.yaml
  config/packages/dev/routing.yaml
  config/packages/framework.yaml
  config/packages/routing.yaml
  config/packages/test/framework.yaml
  config/packages/test/routing.yaml
  config/routes.yaml
  config/services.yaml
  public/index.php
  src/Controller/.gitignore
  src/Kernel.php
  symfony.lock
Labels: feature

#6 add circle ci configuration file
  .circleci/config.yml
Labels: feature

#22 set security bundle in the project
  bestPractices.txt
  composer.json
  composer.lock
  config/bundles.php
  config/packages/security.yaml
  symfony.lock
Labels: MiniFeat

#24 Fix security bundle installation
  composer.json
  composer.lock
Labels: bug

#26 Create Conference Api to manage conference entity
  .env
  .gitignore
  composer.json
  composer.lock
  config/bundles.php
  config/packages/dev/hautelook_alice.yaml
  config/packages/dev/nelmio_alice.yaml
  config/packages/sensio_framework_extra.yaml
  config/packages/test/hautelook_alice.yaml
  config/packages/test/nelmio_alice.yaml
  config/packages/translation.yaml
  config/packages/twig.yaml
  config/routes/dev/twig.yaml
  config/routes/routes.yaml
  docker-compose.yaml
  fixtures/.gitignore
  fixtures/fixtures.yml
  phpcs.xml.dist
  src/Controller/ConferenceController.php
  src/DataFixtures/AppFixtures.php
  src/Entity/Conference.php
  src/Entity/Rate.php
  symfony.lock
  templates/Conference/conference.html.twig
  templates/base.html.twig
Labels: feature

#36 create confernece method implementation
  src/Controller/ConferenceController.php
  src/Form/ConferenceType.php
  templates/Conference/create.html.twig
Labels: enhancement

#46 Master feature def improv
  .circleci/config.yml
  Makefile
  public/css/styles.css
  public/images/bug.png
  public/js/scripts.js
  src/Controller/ConferenceController.php
  src/Controller/SecurityController.php
  src/Controller/SignupController.php
  src/Controller/UserController.php
  src/Entity/Conference.php
  src/Entity/User.php
  src/Form/ConferenceType.php
  src/Form/SignupType.php
  src/Repository/ConferenceRepository.php
  src/Repository/UserRepository.php
  src/Security/ConferenceAuthenticator.php
  templates/Conference/admin.html.twig
  templates/base.html.twig
  templates/conference/about.html.twig
  templates/conference/admin-conference.html.twig
  templates/conference/create-update.html.twig
  templates/conference/user-conference.html.twig
  templates/conference/view.html.twig
  templates/signup/signup.html.twig
  templates/user/user.html.twig
  templates/user/users.html.twig
Labels: feature

#47 Master feature def improv
  .env
  README.md
  composer.json
  composer.lock
  config/bundles.php
  config/packages/dev/swiftmailer.yaml
  config/packages/mailer.yaml
  config/packages/swiftmailer.yaml
  config/packages/test/swiftmailer.yaml
  fixtures/fixtures.yml
  public/css/styles.css
  src/Controller/ConferenceController.php
  src/Controller/SignupController.php
  src/Entity/User.php
  src/Form/ConferenceType.php
  src/Form/SignupType.php
  src/Repository/UserRepository.php
  symfony.lock
  templates/conference/admin-conference.html.twig
  templates/conference/confirmation-view.html.twig
  templates/conference/create-update.html.twig
  templates/conference/registration-confirmed.html.twig
  templates/conference/view.html.twig
  templates/conference/wait-confirmation.html.twig
Labels: enhancement, feature

#48 Update the badge of circleci
  README.md
Labels: bug

#52 add new features
  public/css/styles.css
  src/Controller/ConferenceController.php
  src/Controller/SignupController.php
  src/Controller/UserController.php
  src/Form/UserType.php
  src/Security/ConferenceAuthenticator.php
  templates/base.html.twig
  templates/conference/about.html.twig
  templates/conference/admin-conference.html.twig
  templates/conference/create-update-conference.html.twig
  templates/conference/mail-confirm-registration.html.twig
  templates/conference/success-create-conference.html.twig
  templates/conference/user-conference.html.twig
  templates/signup/registration.html.twig
  templates/user/edit-profile.html.twig
  templates/user/profile.html.twig
  templates/user/user.html.twig
  templates/user/users.html.twig
Labels: feature

#60 change the image used in conefrence view
  public/images/sym.png
  templates/conference/admin-conference.html.twig
Labels: bug
